import { Money } from '../value-objects/Money'

// ─── Input types ──────────────────────────────────────────────────────────────

/**
 * Subset of transaction types relevant to rotation detection.
 * Mirrors the TransactionType enum in the Prisma schema without importing it.
 */
export type TransactionKind =
  | 'EXPENSE'
  | 'INCOME'
  | 'CARD_PAYMENT'
  | 'INTER_CARD_TRANSFER'
  | 'INTEREST_CHARGE'
  | 'FEE'

/** Minimal transaction shape required for rotation analysis. */
export interface TransactionInput {
  id: string
  type: TransactionKind
  /**
   * Explicit inter-card flag. A transaction is a rotation when
   * type === 'INTER_CARD_TRANSFER' OR isInterCard === true.
   * This dual check handles data from both manual input and the Phase 2
   * email tracker (which may classify the same event differently).
   */
  isInterCard: boolean
  /** Amount in CLP (positive integer). */
  amount: number
  /** ID of the card being debited to fund the transfer (source card). */
  sourceCardId: string | null
  date: Date
  description: string
}

/** Monthly revolving rate for a specific card. Used to estimate rotation costs. */
export interface CardRate {
  cardId: string
  /** Monthly revolving rate in percent (e.g., 3.35). */
  monthlyRate: number
}

// ─── Output types ─────────────────────────────────────────────────────────────

/** A single detected inter-card transfer with its estimated cost. */
export interface DetectedRotation {
  transactionId: string
  /** Amount moved between cards, in CLP. */
  amount: number
  sourceCardId: string | null
  date: Date
  description: string
  /**
   * Monthly interest this rotation generates on the source card.
   * Formula: amount × sourceCardMonthlyRate / 100.
   */
  estimatedMonthlyInterest: number
  /**
   * Transfer fees for this rotation.
   * Zero in Phase 1 — Chilean inter-card PAT transfers carry no explicit fee,
   * so the entire cost comes from interest.
   */
  estimatedFees: number
  /** Total monthly cost: estimatedMonthlyInterest + estimatedFees. */
  estimatedMonthlyCost: number
}

/** Full rotation analysis for a set of transactions. */
export interface RotationAnalysis {
  /** Number of inter-card transfer transactions detected. */
  rotationCount: number
  /** Total CLP amount moved between cards in the period. */
  totalVolumeRotated: Money
  /** Total monthly interest generated by all rotations. */
  estimatedMonthlyInterest: Money
  /** Total fees for all rotations (zero in Phase 1). */
  estimatedFees: Money
  /** Total monthly cost: interest + fees. */
  estimatedMonthlyCost: Money
  /** Breakdown per detected rotation. */
  rotations: DetectedRotation[]
  /**
   * True when rotationCount ≥ CAROUSEL_THRESHOLD, indicating the family is
   * cycling debt between cards instead of making real payments.
   */
  isCarouselDetected: boolean
  /**
   * Estimated monthly cost as a percentage of total rotated volume.
   * Rounded to 2 decimal places. Zero when no volume is rotated.
   * Example: 2.87 means the carousel costs ~2.87% of the rotated amount per month.
   */
  costRatePct: number
}

// ─── Constants ────────────────────────────────────────────────────────────────

/**
 * Minimum number of rotations in a period to classify the pattern as a carousel.
 * A single inter-card transfer might be a one-off balance consolidation;
 * two or more suggest an active debt-cycling strategy.
 */
const CAROUSEL_THRESHOLD = 2

/**
 * Fallback monthly revolving rate (%) used when a source card's rate is unknown.
 * Corresponds to the highest revolving rate in the family's portfolio (Santander 3.35%).
 * Using the highest rate is a conservative (worst-case) cost estimate.
 */
const DEFAULT_MONTHLY_RATE = 3.35

// ─── Domain Service ───────────────────────────────────────────────────────────

/**
 * Pure domain service that identifies credit card carousel patterns.
 *
 * Background (Phase 2 context):
 *   Freddy and Rahydee rotate ~$25–30M/month between Santander and Scotiabank cards
 *   to defer real payments. Each rotation appears as an INTER_CARD_TRANSFER on the
 *   source card's statement. This detector quantifies the volume and monthly cost of
 *   that pattern so it can be surfaced as an alert in the dashboard.
 *
 * Phase 1 note:
 *   Manual transaction input will rarely include INTER_CARD_TRANSFER entries.
 *   This service is ready for Phase 2 when the email tracker (NestJS service) starts
 *   pushing parsed statement transactions via POST /api/webhook/transaction.
 */
export class CardRotationDetector {
  /**
   * Analyzes a set of transactions and identifies inter-card transfer rotations.
   *
   * Detection rule: a transaction is a rotation when
   *   `type === 'INTER_CARD_TRANSFER'` OR `isInterCard === true`.
   *
   * Cost per rotation = amount × sourceCardMonthlyRate / 100.
   * Falls back to DEFAULT_MONTHLY_RATE (3.35%) when the source card has no
   * rate entry in `cardRates`.
   *
   * @param transactions - All transactions for the analysis period (month, quarter, etc.).
   * @param cardRates    - Monthly revolving rates keyed by card ID. Optional — if omitted,
   *                       every rotation uses the DEFAULT_MONTHLY_RATE for cost estimation.
   */
  static detectRotations(
    transactions: ReadonlyArray<TransactionInput>,
    cardRates: ReadonlyArray<CardRate> = []
  ): RotationAnalysis {
    const rateMap = new Map(cardRates.map((c) => [c.cardId, c.monthlyRate]))

    const rotationTxs = transactions.filter(
      (tx) => tx.type === 'INTER_CARD_TRANSFER' || tx.isInterCard
    )

    const rotations: DetectedRotation[] = rotationTxs.map((tx) => {
      const rate = resolveRate(tx.sourceCardId, rateMap)
      const estimatedMonthlyInterest = Math.round((tx.amount * rate) / 100)

      return {
        transactionId: tx.id,
        amount: tx.amount,
        sourceCardId: tx.sourceCardId,
        date: tx.date,
        description: tx.description,
        estimatedMonthlyInterest,
        estimatedFees: 0,
        estimatedMonthlyCost: estimatedMonthlyInterest,
      }
    })

    const totalVolume = rotations.reduce((sum, r) => sum + r.amount, 0)
    const totalInterest = rotations.reduce(
      (sum, r) => sum + r.estimatedMonthlyInterest,
      0
    )

    const costRatePct =
      totalVolume > 0
        ? Math.round((totalInterest / totalVolume) * 10_000) / 100
        : 0

    return {
      rotationCount: rotations.length,
      totalVolumeRotated: Money.fromPesos(totalVolume),
      estimatedMonthlyInterest: Money.fromPesos(totalInterest),
      estimatedFees: Money.fromPesos(0),
      estimatedMonthlyCost: Money.fromPesos(totalInterest),
      rotations,
      isCarouselDetected: rotations.length >= CAROUSEL_THRESHOLD,
      costRatePct,
    }
  }
}

// ─── Private helpers ──────────────────────────────────────────────────────────

function resolveRate(
  cardId: string | null,
  rateMap: Map<string, number>
): number {
  if (cardId === null) return DEFAULT_MONTHLY_RATE
  return rateMap.get(cardId) ?? DEFAULT_MONTHLY_RATE
}
